language: node_js
node_js:
  - "8"
branches:
  only:
    - v2
before_script:
  - "npm run examples:build"
install: true
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: v2
  local_dir: ${TRAVIS_BUILD_DIR}/examples/dist
